Week9/Day5/Tor_Kee_Part_2/Hotel/Hotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('visitors.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('staff/', include('staff.urls', namespace='staff')),
]

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/urls.py
from django.urls import path
from . import views
from .views import staff, review_list, booking_create, booking_delete, booking_detail, booking_list, booking_success, booking_update, available_dates

app_name = 'staff'

urlpatterns = [
    path('', views.staff, name='staff'),
    # Reviews
    path('staff/reviews', views.review_list, name='review_list'),
    path('review-success/', views.review_success, name='review-success'),

    # Bookings
    path('bookinglist', views.booking_list, name='booking_list'),
    path('<int:pk>/', views.booking_detail, name='booking_detail'),
    path('createbooking/', views.booking_create, name='booking_create'),
    path('<int:pk>/update/', views.booking_update, name='booking_update'),
    path('<int:pk>/delete/', views.booking_delete, name='booking_delete'),
    path('booking-success/', views.booking_success, name='booking-success'),

    # Avilaible dates
        path('available-dates/', available_dates, name='available_dates'),
]

Week9/Day5/Tor_Kee_Part_2/Hotel/visitors/urls.py
from django.urls import path
from . import views
from .views import HotelDetailView, VacancyListView, InquiryCreateView, create_review, booking_success, available_dates, contact
from .views import booking_list, booking_create, booking_detail, booking_delete, booking_success, booking_update
from .views import contact, contact_success, review_list

app_name = 'visitors'

urlpatterns = [ 
    path('', views.info_page, name='info-page'),

    # Reviews
    path('staff/reviews', views.review_list, name='review_list'),
    path('review-success/', views.review_success, name='review-success'),

    # Bookings
    path('bookinglist', views.booking_list, name='booking_list'),
    path('<int:pk>/', views.booking_detail, name='booking_detail'),
    path('createbooking/', views.booking_create, name='booking_create'),
    path('<int:pk>/update/', views.booking_update, name='booking_update'),
    path('<int:pk>/delete/', views.booking_delete, name='booking_delete'),
    path('booking-success/', views.booking_success, name='booking-success'),

    path('reviews/create/', views.create_review, name='review-create'),

    path('hotels/<int:pk>/', views.HotelDetailView, name='hotel-detail' ),
    path('vacancies/', views.VacancyListView, name='vacancy-list'),
    path('inquiries/create/', views.InquiryCreateView, name='inquiry-create'),

    path('available-dates/', available_dates, name='available_dates'),

    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),
]

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/models.py
from django.db import models
from django import forms

class Availability(models.Model):
    hotel = models.ForeignKey('Hotel', on_delete=models.CASCADE, null=True)
    date = models.DateField()
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True)

    def __str__(self):
        return f'{self.hotel} ({self.date})'

    class Meta:
        verbose_name_plural = 'Availabilities'
        unique_together = ('hotel', 'date')

class Hotel(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Hotels'

class Booking(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True)
    email = models.EmailField()
    check_in = models.DateField()
    check_out = models.DateField()
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    
class Inquiry(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

class Review(models.Model):
    id = models.IntegerField(primary_key=True)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    rating = models.IntegerField()
    name = models.CharField(max_length=20, null=True)
    comment = models.TextField()
    

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['id','hotel', 'rating','name','comment']

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['first_name', 'last_name', 'email', 'check_in', 'check_out', 'hotel']

class InquiryForm(forms.ModelForm):
    class Meta:
        model = Inquiry
        fields = ['name', 'email', 'message']

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Availability
from .models import BookingForm, Booking
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone


# staff landing page
def staff(request):
    return render(request, 'staff_home.html')

# Review
def review_list(request):
    reviews = Review.objects.all()
    if request.method == 'POST':
        review_id = request.POST.get('review_id')
        review = get_object_or_404(Review, pk=review_id)
        review.delete()
        # return redirect('review_list')
    return render(request, 'staff_review.html', {'reviews': reviews})

def review_success(request):
    context = {}
    return render(request, 'review_success.html', context)

# bookings
def booking_list(request):
    bookings = Booking.objects.all()
    return render(request, 'booking_list.html', {'bookings': bookings})


def booking_detail(request, pk):
    booking = get_object_or_404(Booking, pk=pk)
    return render(request, 'booking_detail.html', {'booking': booking})


def booking_create(request):
    if request.method == 'POST':
        bookings = Booking.objects.all()
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save()
            return render(request, 'booking_list.html', {'bookings': bookings})
            # return redirect('booking_detail', pk=booking.pk)
    else:
        form = BookingForm()
    return render(request, 'booking_form.html', {'form': form})


def booking_update(request, pk):
    booking = get_object_or_404(Booking, pk=pk)
    if request.method == 'POST':
        bookings = Booking.objects.all()
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            booking = form.save()
            return render(request, 'booking_list.html', {'bookings': bookings})
            # return redirect('booking_detail', pk=booking.pk)
    else:
        form = BookingForm(instance=booking)
    return render(request, 'booking_form.html', {'form': form})


def booking_delete(request, pk):
    booking = get_object_or_404(Booking, pk=pk)
    if request.method == 'POST':
        booking.delete()
        return redirect('booking_list')
    # If the request method is not POST, render the template as usual
    return render(request, 'booking_delete.html', {'booking': booking})

def booking_success(request):
    context = {}
    return render(request, 'booking_success.html', context)


# algorithm for available dates
def available_dates(request):
    today = timezone.now().date()
    bookings = Booking.objects.filter(check_out__gte=today).order_by('check_in')
    booked_dates = set()
    for booking in bookings:
        current_date = booking.check_in
        while current_date <= booking.check_out:
            booked_dates.add(current_date)
            current_date += timezone.timedelta(days=1)

    dates = []
    current_date = today
    while len(dates) < 365:
        if current_date not in booked_dates:
            dates.append(current_date)
        current_date += timezone.timedelta(days=1)

    context = {'dates': dates}
    return render(request, 'available_dates.html', context)

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/available_dates.html
{% extends 'base.html' %}

{%load static %}

{% block content %}
    <h1>Available Dates</h1>
    <hr>
    <div class="row">
        {% for date in dates %}
        <div class="col-md-3 mb-3">
            <div class="card bg-secondary text-white">
                <div class="card-body">
                    <h5 class="card-title">{{ date|date:"l" }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ date|date:"F j" }}</h6>
                    <p class="card-text">{{ date|date:"N" }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/booking_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-4">Booking Details</h1>
    <table class="table table-striped">
      <tbody>
        <tr>
          <th scope="row">First Name</th>
          <td>{{ booking.first_name }}</td>
        </tr>
        <tr>
          <th scope="row">Last Name</th>
          <td>{{ booking.last_name }}</td>
        </tr>
        <tr>
          <th scope="row">Email</th>
          <td>{{ booking.email }}</td>
        </tr>
        <tr>
          <th scope="row">Check In</th>
          <td>{{ booking.check_in }}</td>
        </tr>
        <tr>
          <th scope="row">Check Out</th>
          <td>{{ booking.check_out }}</td>
        </tr>
        <tr>
          <th scope="row">Hotel</th>
          <td>{{ booking.hotel }}</td>
        </tr>
      </tbody>
    </table>
    <a href="{% url 'staff:booking_list' %}" class="btn btn-primary">Back to List</a>
  </div>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/booking_form.html
{% extends 'base.html' %}

{% load static %}


{% block title %}Book a Room{% endblock %}

{% block content %}
    <h1>Book a Room</h1>
    <hr>
    <form method="post" class="my-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Book Now</button>
        <a href="{% url 'visitors:available_dates' %}" class="btn btn-primary">Check availability</a>

    </form>

    <!-- Hidden modal window -->
<div id="booking-success-modal" class="modal" style="display:none;">
    <div class="modal-content">
        <h2>Your booking has been successful!</h2>
        <p>Thank you for choosing our hotel.</p>
    </div>
</div>

{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/booking_form.js' %}"></script>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/booking_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="container my-5">
    <h1 class="mb-4">List Bookings</h1>
    <a href="{% url 'staff:booking_create' %}" class="btn btn-primary mb-3">Create Booking</a>
    {% if bookings %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Check In</th>
            <th scope="col">Check Out</th>
            <th scope="col">Hotel</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for booking in bookings %}
            <tr>
              <th scope="row">{{ booking.id }}</th>
              <td>{{ booking.first_name }}</td>
              <td>{{ booking.last_name }}</td>
              <td>{{ booking.email }}</td>
              <td>{{ booking.check_in }}</td>
              <td>{{ booking.check_out }}</td>
              <td>{{ booking.hotel }}</td>
              <td>
                <a href="{% url 'visitors:booking_detail' booking.pk %}" class="btn btn-sm btn-info mr-2">Details</a>
                <a href="{% url 'visitors:booking_update' booking.pk %}" class="btn btn-sm btn-primary mr-2">Edit</a>
                <form action="{% url 'visitors:booking_delete' booking.pk %}" method="post" class="d-inline">
                  {% csrf_token %}
                  <input type="hidden" name="booking_id" value="{{ booking.pk }}">
                  <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No bookings yet.</p>
    {% endif %}
  </div>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/booking_success.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Booking Successful{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ title }}</div>

                    <div class="card-body">
                        <p>Your booking has been successful!</p>
                        <p>Thank you for choosing our hotel.</p>
                        <a href="{% url 'info-page' %}" class="btn btn-primary">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/delete_booking.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <h1>Delete Booking</h1>
    <p>Are you sure you want to delete the booking for {{ booking.first_name }} {{ booking.last_name }}?</p>
    <form action="{% url 'staff:delete_booking' booking_id %}" method="post" class="d-inline">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'staff:list_bookings' %}" class="btn btn-secondary ml-2">Cancel</a>
    </form>
  </div>
{% endblock %}

Week9/Day5/Tor_Kee_Part_2/Hotel/staff/templates/staff_home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<body style="background-color: black;">
  <div class="container my-5">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="text-center mb-5" style="color: white;">Welcome Staff members!</h1>
        
      </div>
    </div>
  </div>

  <div class="container">
    <table class="table table-bordered text-white">
      <thead>
        <tr>
          <th scope="col" class="col-sm-3">LINK</th>
          <th scope="col" class="col-sm-9">DESCRIPTION</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="{% url 'visitors:review_list' %}">Reviews</a></td>
          <td>Delete negative comments and keep positive vibes for future visitors.</td>
        </tr>
        <tr>
          <td><a href="{% url 'visitors:booking_list' %}">Bookings</a></td>
          <td>View and modify bookings here.</td>
        </tr>
        <tr>
          <td><a href="{% url 'visitors:available_dates' %}">Available Dates</a></td>
          <td>View the dates available for booking.</td>
        </tr>
        <tr>
          <td><a href="http://127.0.0.1:8000/admin/visitors/contact/" target="_blank">Visitors Messages</a></td>
          <td>View the messages sent by visitors</td>
        </tr>
      </tbody>
    </table>
  </div>

</body>


{% endblock %}